### ISSUE TITLE
php artisan error/solution

### ISSUE THREAD

**Issue by guilhermefigueiredo** [ukfast/fnm-webui#1]
the command: php artisan migrate --seed

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 byte

the solution I found was to do the following:

Go to App\Providers\AppServiceProvider.php.
Add this to provider  use Illuminate\Support\Facades\Schema; in top.
Inside the Boot function Add this Schema::defaultStringLength(191);

BR!

**Comment by laf** [comment]
Thanks for the report @guilhermefigueiredo. It would be good if you could submit a pull request with the necessary fixes as that does look like the correct fix.

**Comment by paulocoimbrati** [comment]
I'll send a PR as requested by my friend @guilhermefigueiredo

**Comment by Knot3n** [comment]
Strange, on CentOS i dont have that problem.

**Comment by laf** [comment]
@Knot3n It's down to the version of MySQL afaik. If you have a more recent version then it's ok.

**Comment by laf** [comment]
Fixed in #2
