### ISSUE TITLE
Banned details missing

### ISSUE THREAD

**Issue by tehnicadmin** [ukfast/fnm-webui#10]
When i have an ip banned i can see there but with no details/log
what i need to configure to see banned details?

**Comment by tehnicadmin** [comment]
Also when access https://my.fnm.domain.com/webhook i receive a big error:

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException thrown with message ""

Stacktrace:
#26 Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:255
#25 Illuminate\Routing\RouteCollection:methodNotAllowed in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:242
#24 Illuminate\Routing\RouteCollection:getRouteForMethods in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:176
#23 Illuminate\Routing\RouteCollection:match in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
#22 Illuminate\Routing\Router:findRoute in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php:614
#20 Illuminate\Routing\Router:dispatch in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/public/public/index.php:55

**Comment by chenhaw** [comment]
Having the same issue previously.

What we did to have banned details was changing the `packet_dump` column in `dc` table from text to mediumtext type.

**Comment by miff2000** [comment]
> Also when access https://my.fnm.domain.com/webhook i receive a big error:
> 
> Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException thrown with message ""

Hey @tehnicadmin 

That error `MethodNotAllowed` exception usually occurs when you use the wrong HTTP method to access a URL. For instance, if you try to use a browser to access a non-`GET` route. Looking at the `/webhook` one, I can see it's a `POST` method route:

* <https://github.com/ukfast/fnm-webui/blob/31590996b11557d8ef576650c9f15889d71dd957/routes/web.php#L21>

If you want to use that route, you would need to use the POST method to send data, something like this:

* <https://linuxize.com/post/curl-post-request/>

What were you trying to do at the time? Are the ban details still missing?

**Comment by miff2000** [comment]
Also, I guess you were trying to work out what information should be sent in the webhook?

This file will give you an idea of what data needs to be in it:

* <https://github.com/ukfast/fnm-webui/blob/master/app/Http/Controllers/WebhookController.php>

Let me know if you need any more info, and if not, I'll close the issue

**Comment by miff2000** [comment]
I'm going to close this issue. If you have any more problems, please let us know
