### ISSUE TITLE
Trying to access array offset on value of type bool (View: /home/xxx/domains/fnm.xxx.com/resources/views/home.blade.php)

### ISSUE THREAD

**Issue by ServerionNL** [ukfast/fnm-webui#15]
Hi,

I have an issue suddenly after working with the tool for days... I get this error:

https://prnt.sc/wnhwij

How do I solve this?

Desmond

**Comment by ServerionNL** [comment]
Found it, line 83 of home.blade.php

needs to change
`                @if(count($dcs) == 0) `

to
`                @if(count($dcs)) == 0 `

**Comment by laf** [comment]
The current line you've changed was correct according to the Laravel docs:

https://laravel.com/docs/8.x/blade#if-statements

**Comment by miff2000** [comment]
Is this issue still happening @ServerionNL?

I've not heard any other reports of it happening. The error in your screenshot is pointing to this line in the code:

* https://github.com/ukfast/fnm-webui/blob/a111ed0/resources/views/home.blade.php#L98

I wonder if something is wrong in this logic 
```php
@if ($dc->license()['licensed_bandwidth'] === 0 || $dc->license()['expiration_date_carbon'] < \Carbon\Carbon::now())
```

If you can let me know, I'll have a dig further into it. It would be good to know if you had a license installed properly a the time, and if there could have been any issues with time sync on the server it was running on

**Comment by miff2000** [comment]
No response so I'm assuming it wasn't an issue with the application itself. Let me know if this is incorrect. I'll close this issue down in the meantime

**Comment by pavel-odintsov** [comment]
I think it's still happens as we have another report of this issue.

![photo_2023-04-11_16-38-38](https://user-images.githubusercontent.com/2744166/231215431-b8ec69b8-dc66-4ba9-affe-a8d08808715c.jpg)
![photo_2023-04-11_16-38-35](https://user-images.githubusercontent.com/2744166/231215436-71111869-b392-41a7-a0a7-c03518a0cb5e.jpg)
