### ISSUE TITLE
Feature Request: History User Log

### ISSUE THREAD

**Issue by Knot3n** [ukfast/fnm-webui#3]
Hello, 

would it be possible and "easy" to add a feature to see a history log for users?
What they have changed (BAN, UNBAN - etc.

We would be thankful to have something like that.

**Comment by laf** [comment]
Thanks for the feature request.

Just to be open, this isn't a project that we actively develop. Whilst one of the team will probably get round to adding features like this, we would prioritise what's important to us first.

We released the project to the community with the hope that others would contribute *hint* *hint* :)

**Comment by Knot3n** [comment]
Hey laf,

thanks for your reply. 
We would be thankful :) - i understand and will try to contribute what i can.

**Comment by leytonreed** [comment]
Hello @Knot3n,

Just seen this request - it's something I'd have liked to implemented on release, but as @laf mentioned, we didn't need it prioritising at the time.

However, I did add some middleware here:

https://github.com/ukfast/fnm-webui/blob/master/app/Http/Middleware/UserHeader.php#L23

This adds an "X-Authenticated-User" HTTP header to responses with the logged in users' email address.

You could then use a custom Apache or NGINX log format to log the content of that header into your access logs for audit purposes.

Not quite fully featured - but a good enough to get an idea of "who deleted that hostgroup" when you need it.

Cheers :)
