### ISSUE TITLE
DC create - Error 500

### ISSUE THREAD

**Issue by Knot3n** [ukfast/fnm-webui#4]
Hello,

since i reinstalled the webui, im getting a Error 500 without error logs when i try to create a DC in the webui. 
I just restarted the Fastnetmon Server and restarted the API Web service etc. 

> 62.xxxx - - [17/Apr/2019:09:53:07 +0200] "GET /dc/create HTTP/2.0" 200 11805 "https://fnm.xxxxx.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
62.xxxxxx - - [17/Apr/2019:09:53:07 +0200] "GET /css/main.css HTTP/2.0" 200 1443 "https://fnm.xxxxxx.com/dc/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
62.xxxxxx - - [17/Apr/2019:09:53:20 +0200] "POST /dc HTTP/2.0" 500 10323 "https://fnm.xxxx.com/dc/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
62.xxxxxx - - [17/Apr/2019:09:53:20 +0200] "GET /svg/500.svg HTTP/2.0" 200 15305 "https://fnm.xxxx.com/dc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"

> web_api_host: 212.xxxxxxxx
web_api_login: ddos
web_api_password: xxxxxxxxxx
web_api_port: 10007

Could i help to debug this so we can re-use this webui?

Thanks

**Comment by leytonreed** [comment]
@Knot3n - Could you have a look in `$INSTALLDIR/storage/logs` for the current log file, and see what is added when you retry the POST?

If this isn't being actively used, you could also enable debugging mode in your `.env` file to show errors instead of the "Error 500" page:

```
APP_ENV=local
APP_DEBUG=true
```

...however please note that this may display secrets in the error messages (like FNM API credentials).

**Comment by Knot3n** [comment]
Hello,

see below

`[2019-04-17 09:21:00] local.ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'api_password' at row 1 (SQL: insert into `dc` (`name`, `active`, `description`, `api_url`, `api_username`, `api_password`, `allowed_ip`, `updated_at`, `created_at`) values (test22222, 1, , http://xxxxxx:10007/, ddos, eyJpdiI6Ik1tRjNFckJMMnBKTHBBdnJ6V2h6UEE9PSIsInZhbHVlIjoiQTU4TVdyRnB6M0RnSnEwb1Z5cTNyTUpOaDV1MCtJM3lpdEdwbnRXWmRETT0iLCJtYWMiOiJhZDM3ODg0NGEyM2Y2ZjE5MGE2ZDg1YWZjMWUwMmE5ZjQyODNlNjE4ZTBlMTQwODhmMWE3OTVkNTcxMWU3MTEyIn0=, xxxxxxx, 2019-04-17 09:21:00, 2019-04-17 09:21:00)) {"userId":1,"email":"admin@localhost","exception":"[object] (Illuminate\\Database\\QueryException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'api_password' at row 1 (SQL: insert into `dc` (`name`, `active`, `description`, `api_url`, `api_username`, `api_password`, `allowed_ip`, `updated_at`, `created_at`) values (test22222, 1, , http://xxxxxx:10007/, ddos, eyJpdiI6Ik1tRjNFckJMMnBKTHBBdnJ6V2h6UEE9PSIsInZhbHVlIjoiQTU4TVdyRnB6M0RnSnEwb1Z5cTNyTUpOaDV1MCtJM3lpdEdwbnRXWmRETT0iLCJtYWMiOiJhZDM3ODg0NGEyM2Y2ZjE5MGE2ZDg1YWZjMWUwMmE5ZjQyODNlNjE4ZTBlMTQwODhmMWE3OTVkNTcxMWU3MTEyIn0=, xxxxxxx, 2019-04-17 09:21:00, 2019-04-17 09:21:00)) at /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'api_password' at row 1 at /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)
[stacktrace]
#0 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `dc...', Array, Object(Closure))
#1 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `dc...', Array, Object(Closure))
#2 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `dc...', Array)
#3 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `dc...', Array)
#4 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2595): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `dc...', Array, 'id')
#5 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1318): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(823): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(788): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(651): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(790): Illuminate\\Database\\Eloquent\\Model->save()
#10 /opt/fnm/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\DC))
#11 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(791): tap(Object(App\\DC), Object(Closure))
#12 /opt/fnm/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create(Array)
#13 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1608): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'Create', Array)
#14 /opt/fnm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\\Database\\Eloquent\\Model->__call('Create', Array)
#15 /opt/fnm/app/Http/Controllers/DCController.php(67): Illuminate\\Database\\Eloquent\\Model::__callStatic('Create', Array)
#16 [internal function]: App\\Http\\Controllers\\DCController->store(Object(Illuminate\\Http\\Request))
#17 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#18 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#19 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\DCController), 'store')
#20 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#21 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#22 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /opt/fnm/app/Http/Middleware/IsAdmin.php(19): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\IsAdmin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /opt/fnm/app/Http/Middleware/UserHeader.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\UserHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /opt/fnm/app/Http/Middleware/IsActive.php(19): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\IsActive->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /opt/fnm/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /opt/fnm/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /opt/fnm/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /opt/fnm/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /opt/fnm/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#56 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#57 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#58 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#59 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#60 /opt/fnm/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /opt/fnm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /opt/fnm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 /opt/fnm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#78 /opt/fnm/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#79 {main}
"}`

**Comment by leytonreed** [comment]
Thanks for that - the important part of the error is here:

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'api_password' at row 1 (SQL: insert into dc (name, active, description, api_url, api_username, api_password, allowed_ip, updated_at, created_at) values (test22222, 1, , http://xxxxxx:10007/, ddos, `

As per the following DB migration, the `api_password` field is treated as a default string:
https://github.com/ukfast/fnm-webui/blob/master/database/migrations/2018_11_29_101328_create_dcs_table.php#L25

The default length for strings is configured here:
https://github.com/ukfast/fnm-webui/blob/3fad92590d3373fc6925ddaa43419b1edb7c8a02/app/Providers/AppServiceProvider.php#L17

There are a couple of options here:

1. Reduce the size of the password to below 191 characters.
2. (if you don't have any data you need in the DB) Update the AppServiceProvider.php to use a larger size, then reinstall by dropping the tables and re-running the DB migration.
3. (if you have data that you need in the DB) Update the DB schema by either creating a migration to update the length, or via an `ALTER TABLE` in MySQL.

https://stackoverflow.com/questions/36469496/laravel-5-migration-change-length-of-existed-column
https://stackoverflow.com/questions/1279568/how-can-i-modify-the-size-of-column-in-a-mysql-table

Assuming that you have restrictive firewall rules in place for the API port, then the first option should be relatively safe.

As a future MR, the validation on that field should probably check that the string entered is under the `Schema::defaultStringLength` size.

**Comment by Knot3n** [comment]
Hello,

thank you very much for your fast help & support.

increaseing the size to 255 characters helped here, the webui can connect to the api successfull now.
