### ISSUE TITLE
IPs and Hostgroups lists empty

### ISSUE THREAD

**Issue by dmayan-ss** [ukfast/fnm-webui#6]
Hi,

I installed the UI today. I could connect to my Fastnetmon instance, only when I altered the DC table api-password field to be 255 chars.

Also my IP and hostgroups lists are empty.

Anything I could do?

**Comment by leytonreed** [comment]
Hey @dmayan-ss,

Are you adding a blank (new) fastnetmon instance into the UI, or a fastnetmon instance that's already configured?

At the moment, any elements (host groups, IP ranges, etc) need to be created via the UI for them to appear.

Cheers.

**Comment by leytonreed** [comment]
As to the API Password issue, this was discussed in the following issue:

https://github.com/ukfast/fnm-webui/issues/4

Ideally, a pull request will be made to make it more clear that the size of that field is restricted by the default string length to avoid the HTTP 500.

**Comment by Knot3n** [comment]
Hey @leytonreed - would it be maybe better use utf8 instaed of utf8mb4 ? 

I try to fix this for future but a bit "help" would be nice. 

Found that: 

> Issue occurs when database configuration related to full support for the utf8mb4 charset is incorrect; MySQL > 5.7 & MariaDB > 10.2 doesn't have this issue because they default to the correct configuration values; this fix solves the issue for older versions of MySQL and MariaDB without requiring database server configuration changes.

> The root cause of the issue with the utf8mb4 encoding is that both InnoDB and MyISAM have too low of an index key prefix limit (767 bytes and 1000 bytes respectively) to properly store 255 4-byte characters; which would take 1024 bytes. See the docs on InnoDB limitations: https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

> In MySQL >= 5.7 & MariaDB >= 10.2 this limit has been bumped to 3076 bytes by the changing of the default value of the `innodb_large_prefix` configuration property (introduced in MySQL 5.5) to true; which is what bumps up the limit. In order to manually set that property to true on earlier versions, `innodb_file_format` must be set to `BARRACUDA` and `row_format` must be `DYNAMIC` or `COMPRESSED`. 
> This change fixes the issue by changing the default string length to 191 (total of 764 bytes, within the older size limit) when the MySQL database config is detected to be using the utf8mb4 charset.


So - a W/A would be that older MariaDB/MySQL Users should use innodb_file_format instead of key lenght 191?

**Comment by dmayan-ss** [comment]
Thanks for your reply!! I didn´t realize that I had the issues tab filtered to only open. ;)

I will be contributing since we are a large ISP on South Patagonia and we rely a lot on Fastnetmon. This tool is a great aid to manage it.

Keep up the amazing work and tell me if we can help in any way.

Diego

> Hey @dmayan-ss,
> 
> Are you adding a blank (new) fastnetmon instance into the UI, or a fastnetmon instance that's already configured?
> 
> At the moment, any elements (host groups, IP ranges, etc) need to be created via the UI for them to appear.
> 
> Cheers.
