### ISSUE TITLE
Hostgroups from FNM not synced to UI

### ISSUE THREAD

**Issue by absynth47215** [ukfast/fnm-webui#7]
In my test deployment for FNM pro, I am using the "baseline_magician" binary to create thresholds and baselines. It creates the appropriate hostgroups, as evidenced by fcli show hostgroup. However, the web ui only shows the old, manually created (via web ui) hostgroups. 

I purged the laravel cache by using php artisan cache:clear in the project directory, but to no avail. Is there anything specific I need to do to synchronize the hostgroups with FNM?

**Comment by leytonreed** [comment]
Hello @absynth47215,

Only items (host groups, ranges, etc) that were created within the UI will show up. 

If anything is manually created outside the fnm-webui will be included in the overall stats, but not in the detailed statistics.

You could duplicate your rules in the UI and arrange a cutover, but I'd recommend testing that in a staging environment first.

It is possible to write an importer with a few code changes to remove the enforcement of the naming schemes, feel free to make a pull request if you get that working :)

Cheers,
Leyton

**Comment by laf** [comment]
Thanks @leytonreed :)
