### ISSUE TITLE
Artisan error

### ISSUE THREAD

**Issue by hidagar** [ukfast/fnm-webui#9]
Hi,

I have this error 
sudo php artisan migrate --seed
PHP Warning:  require(/var/www/fnm-webui/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/fnm-webui/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/fnm-webui/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/fnm-webui/artisan on line 18

Anyone can help me?

Thanks

**Comment by laf** [comment]
Try running `composer install` first

**Comment by hidagar** [comment]
Hi Iaf, 

I installed composer using this https://websiteforstudents.com/how-to-install-php-composer-on-ububuntu-16-04-17-10-18-04/

And I have the same error

**Comment by miff2000** [comment]
Hey @hidagar. Apologies to dig up an old issue, but did you work out the issue with this in the end?
